### ISSUE TITLE
Sanitizing/Removing Iframe attributes properly

### ISSUE THREAD

**Issue by pankajpatel** [jbhannah/amperize#126]
This issue is coming form [TryGhost/Ghost/issues/10796](https://github.com/TryGhost/Ghost/issues/10796)

As we can see from here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/validator-amp-iframe.protoascii

The iframe attribute needs proper sanitization as some attributes accept no value but their presence and some attrs allow values from [`0`, `1`]

- `scrolling`: value as 0 or 1
- `frameborder`: value as 0 or 1
- `allowtransparency`: presence and no value
- `allowfullscreen`: presence and no value

**Comment by rolxhdz** [comment]
Hello! Do you have any news on this?
I'm experiencing the issue with Spotify widget on a blog post: 

![Snap4](https://user-images.githubusercontent.com/8505040/72349304-e0f4de00-36a1-11ea-83ae-ad5f0fee3afa.jpg)

Amp version: https://rolhdz.net/detras-de-las-canciones-erika-ender/amp/

**Comment by jbhannah** [comment]
@pankajpatel @rolxhdz I've just pushed version 0.6.1, try updating and see if that fixes your issues.

**Comment by cobbweb** [comment]
The `scrolling` attribute needs to be `yes|no|auto`, using `0|1` fails AMP validation.

**Comment by jayneil** [comment]
@jbhannah - I'm still facing the same issue as seen in the attached screenshot. How do I fix it? I'm running Ghost 3.37.1

<img width="1280" alt="Spotify Embed issue" src="https://user-images.githubusercontent.com/3578243/121787235-f0c46a80-cb92-11eb-9410-c459a26465d9.png">
